title: "Bienvenue sur le portail Silex..."
info: "Cadriciel de développement WEB en Yaml et Sql"
icon_file: "silex.svg"

# Liste des applications gérées par le portail
applications:
- admin
- jecompte
