[package]
name = "rustic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.29.1", features = ["full"] }
sqlx = { version = "0.7.1", features = [ "runtime-tokio-rustls", "postgres", "macros" ] }
