# application ADMIN de beedul
appid: "admin"
title: "Gestion des Utilisateurs"
image: "groups.png"
group: "admin"
menu:
- tableid: "users"
  viewid: "vall"
  in_footer: true
- tableid: "groups"
  viewid: "vall"
  in_footer: true
- tableid: "users_groups"
  viewid: "vall"
  in_footer: true
