# table USERS
setting:
  alias_db: admin
  key: user_name
  icon_name: "user"

elements:
  user_name:
    order: 10
    type_element: text
    label_long: "Nom ou pseudo"
    label_short: "Nom ou pseudo"
    pattern: "[a-zA-Z0-9]+"
    required: true
  user_password:
    order: 30
    type_element: password
    label_long: "Mot de passe"
    pattern: "[a-zA-Z0-9_-]+"
    required: true
    min_length: 3
  user_email:
    order: 40
    type_element: email
    label_long: "Email"
    label_short: "Email"
    required: true
  user_is_admin:
    order: 50
    type_element: checkbox
    label_long: "Administrateur"
    label_short: "Admin"
    col_align: center
    with_sum: true
  user_groupes:
    order: 60
    type_element: tag
    label_long: "Groupes"
    label_short: "Groupes"
    width: xl
    items_sql: "select group_id as key, group_id as label from groups order by group_id"
  user_subscription:
    order: 70
    type_element: amount
    label_long: "Cotisation"
    label_short: "Cotisation"
    with_sum: true
  _pwd_change:
    order: 100
    type_element: button
    label_long: "Changer le mot de passe..."
    params:
      url: "/edit/admin/users/vall/fpwd/{user_name}"
  _card_MDP:
    order: 200
    type_element: card
    label_long: "Sécurité"
    icon_name: lock
    params:
      formid: fmdp
  _new_password:
    type_element: password
    label_long: "Nouveau mot de passe"
    pattern: "[a-zA-Z0-9_-]+"
    required: true
    min_length: 3
  _confirm_password:
    type_element: password
    label_long: "Confirmer le mot de passe"
    pattern: "[a-zA-Z0-9_-]+"
    required: true
    min_length: 3

views:
  vall:
    form_view: fview
    form_add: fadd
    form_edit: fedit
    # type_view: card
    type_view: table
    group: admin
    deletable: true
    title: "Comptes Utilisateurs"
    icon_name: user
    order_by: user_name
    with_sum: true
    card:
      header:
        - user_name
      meta:
        - user_email
      description:
      extra:
        - user_is_admin
      footer:
        - user_groupes
    elements:
      user_name:
      user_email:
        hide_on_mobile: true
      user_is_admin:
        hide_on_mobile: true
      user_groupes:
      user_subscription:
    filters:
    - user_name
    - user_email
    - user_is_admin
    - user_groupes

  vprofil:
    form_view: fprofil
    form_edit: fedit_owner
    group: owner
    title: "Mon profil"
    icon_name: user
    order_by: user_name
    card:
      header:
        - user_name
      meta:
        - user_email
      description:
      extra:
        - user_is_admin
        - user_groupes
    elements:
      user_name:
      user_email:
      user_is_admin:
      user_groupes:
      user_subscription:

forms:
  fadd:
    title: "Fiche Compte"
    groupe: admin
    elements:
      user_name:
        order: 10
      user_email:
        order: 20
  fedit:
    title: "Fiche compte"
    group: admin
    elements:
      _card0:
        type_element: card
        order: 1
      user_name:
        order: 10
      user_email:
        order: 20
      _card1:
        type_element: card
        order: 100
      user_groupes:
        order: 110
      _card2:
        type_element: card
        order: 200
      user_is_admin:
        order: 210
      _card3:
        type_element: card
        order: 300
      user_subscription :
        order: 310
  fview:
    title: "Fiche Compte"
    group: admin
    elements:
      user_name:
        order: 10
      user_email:
        order: 20
      user_subscription:
        order: 30
      _card_MDP:
        order: 100
      user_is_admin:
        order: 110
      user_groupes:
        order: 120
      _pwd_change:
        order: 130
      _view_groups:
        order: 200
        type_element: view
        params:
          tableid: users_groups
          viewid: vall
          where_sql: users_groups.user_name = '{user_name}'

  fprofil:
    title: "Mon profil"
    group: owner
    elements:
      user_name:
        order: 10
      user_email:
        order: 20
      _card_MDP:
        order: 30
      user_is_admin:
        order: 50
      user_groupes:
        order: 60
      _pwd_change:
        order: 70
  fedit_owner:
    title: "Fiche compte"
    group: owner
    elements:
      user_name:
        order: 10
      user_email:
        order: 20
  fpwd:
    title: "Changer le mot de passe"
    group: owner
    elements:
      user_name:
        order: 10
        read_only: true
      _new_password:
        order: 20
      _confirm_password:
        order: 30
        # protected: true
    check_sqlite:
      - "select 'les mots de passe ne sont pas identiques' where '{_new_password}' <> '{_confirm_password}' "
    post_sql:
      - "update users set user_password = '{_new_password}' where user_name = '{user_name}'"
  fmdp:
    title: "Sécurité"
    group: admin
    elements:
      user_name:
        order: 10
        read_only: true
      user_is_admin:
        order: 30
      user_groupes:
        order: 40
