# Table books de la table books.sqlite
setting:
  alias_db: books
  key: id
  icon_name: "book"

elements:
  id:
    type_element: counter
    label_long: "n°"
    label_short: "n°"
  titre:
    type_element: textarea
    label_long: "Titre"
    label_short: "Titre"
  auteur:
    type_element: text
    label_long: "Auteur"
    label_short: "Auteur"
  editeur:
    type_element: text
    label_long: "Éditeur"
    label_short: "Éditeur"
  note:
    type_element: radio
    label_long: "Note"
    label_short: "Note"
    items:
      - key: "1"
        label: "1"
      - key: "2"
        label: "2"
      - key: "3"
        label: "3"
      - key: "4"
        label: "4"
      - key: "5"
        label: "5"
  commentaire:
    type_element: textarea
    label_long: "Commentaire"
    label_short: "Commentaire"

views:
  vall:
    form_add: fedit
    form_edit: fedit
    deletable: false
    type_element: table
    title: "Books"
    icon_name: book
    order_by: "titre"
    elements:
      id:
        order: 10
      titre:
        order: 20
      auteur:
        order: 30
      editeur:
        order: 40
      note:
        order: 50
      commentaire:
        order: 60

forms:
  fedit:
    title: "Book"
    icon_name: book
    elements:
      id:
        order: 10
      titre:
        order: 20
      auteur:
        order: 30
      editeur:
        order: 40
      note:
        order: 50
      commentaire:
        order: 60
